### ISSUE TITLE
broken in python 3.10 because the attribute MutableMapping has been removed from the module collections

### ISSUE THREAD

**Issue by mathob** [SemaphoreSolutions/s4-clarity-lib#36]
`Python 3.10.6 (main, Aug  5 2022, 16:21:03) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Python shell history and tab completion are enabled.
>>> from s4.clarity.scripts import TriggeredStepEPP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pkg/lib/python3.10/site-packages/s4/clarity/__init__.py", line 12, in <module>
    from ._internal.lazy_property import lazy_property
  File "/opt/pkg/lib/python3.10/site-packages/s4/clarity/_internal/__init__.py", line 6, in <module>
    from .fields import FieldsMixin
  File "/opt/pkg/lib/python3.10/site-packages/s4/clarity/_internal/fields.py", line 163, in <module>
    class FieldsDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'`

**Comment by smallsco** [comment]
Thank you for the report - we have just released version 1.4.0 which adds support for Python 3.10.
